apiVersion: v1
kind: Service
metadata:
  name: tower-defense-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: tower-defense-game
